# Generated by Django 4.1.3 on 2023-03-23 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('price', models.IntegerField()),
                ('offerprice', models.IntegerField()),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='places')),
            ],
        ),
    ]
