# Generated by Django 4.1.3 on 2023-03-23 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Places',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('price', models.IntegerField()),
                ('offerprice', models.IntegerField()),
                ('description', models.TextField()),
                ('place', models.CharField(choices=[('kL', 'kerala'), ('KR', 'Karnataka'), ('ND', 'Newdelhi'), ('UT', 'utterpradesh'), ('PR', 'Pareece'), ('ID', 'Indonesia'), ('GR', 'Greece')], max_length=3)),
                ('image', models.ImageField(upload_to='places')),
            ],
        ),
        migrations.DeleteModel(
            name='Place',
        ),
    ]
