# Generated by Django 4.1.3 on 2023-03-24 07:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('travelapp', '0002_places_delete_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='places',
            name='place',
            field=models.CharField(choices=[('KL', 'Kerala'), ('KR', 'Karnataka'), ('AP', 'Andrapradesh'), ('GO', 'Goa'), ('ND', 'Newdelhi'), ('UT', 'Utterpradesh'), ('PR', 'Pareece'), ('ID', 'Indonesia')], max_length=3),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('locality', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('mobile', models.IntegerField(default=0)),
                ('zipcode', models.IntegerField()),
                ('state', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
