# Generated by Django 4.1.3 on 2023-03-26 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0004_orderplaced_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='product',
            new_name='place',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='quantity',
        ),
        migrations.DeleteModel(
            name='OrderPlaced',
        ),
    ]
